//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.PrintersAndPapers
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Paper type.
    /// </summary>
    // *** Start programmer edit section *** (PaperType CustomAttributes)

    // *** End programmer edit section *** (PaperType CustomAttributes)
    [AutoAltered()]
    [Caption("Paper type")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("PaperTypeE", new string[] {
            "Name as \'Name\'"})]
    [View("PaperTypeL", new string[] {
            "Name as \'Name\'"})]
    public class PaperType : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        // *** Start programmer edit section *** (PaperType CustomMembers)

        // *** End programmer edit section *** (PaperType CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (PaperType.Name CustomAttributes)

        // *** End programmer edit section *** (PaperType.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (PaperType.Name Get start)

                // *** End programmer edit section *** (PaperType.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (PaperType.Name Get end)

                // *** End programmer edit section *** (PaperType.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (PaperType.Name Set start)

                // *** End programmer edit section *** (PaperType.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (PaperType.Name Set end)

                // *** End programmer edit section *** (PaperType.Name Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "PaperTypeE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View PaperTypeE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("PaperTypeE", typeof(IIS.PrintersAndPapers.PaperType));
                }
            }
            
            /// <summary>
            /// "PaperTypeL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View PaperTypeL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("PaperTypeL", typeof(IIS.PrintersAndPapers.PaperType));
                }
            }
        }
    }
}
