//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.PrintersAndPapers
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Printer type.
    /// </summary>
    // *** Start programmer edit section *** (PrinterType CustomAttributes)

    // *** End programmer edit section *** (PrinterType CustomAttributes)
    [AutoAltered()]
    [Caption("Printer type")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("PrinterTypeE", new string[] {
            "Name as \'Name\'"})]
    [View("PrinterTypeL", new string[] {
            "Name as \'Name\'"})]
    public class PrinterType : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        // *** Start programmer edit section *** (PrinterType CustomMembers)

        // *** End programmer edit section *** (PrinterType CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (PrinterType.Name CustomAttributes)

        // *** End programmer edit section *** (PrinterType.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (PrinterType.Name Get start)

                // *** End programmer edit section *** (PrinterType.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (PrinterType.Name Get end)

                // *** End programmer edit section *** (PrinterType.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (PrinterType.Name Set start)

                // *** End programmer edit section *** (PrinterType.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (PrinterType.Name Set end)

                // *** End programmer edit section *** (PrinterType.Name Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "PrinterTypeE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View PrinterTypeE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("PrinterTypeE", typeof(IIS.PrintersAndPapers.PrinterType));
                }
            }
            
            /// <summary>
            /// "PrinterTypeL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View PrinterTypeL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("PrinterTypeL", typeof(IIS.PrintersAndPapers.PrinterType));
                }
            }
        }
    }
}
