//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.PrintersAndPapers
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Printer paper.
    /// </summary>
    // *** Start programmer edit section *** (PrinterPaper CustomAttributes)

    // *** End programmer edit section *** (PrinterPaper CustomAttributes)
    [AutoAltered()]
    [Caption("Printer paper")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("PrinterPaperE", new string[] {
            "PaperType as \'Paper type\'",
            "PaperType.Name as \'Name\'"}, Hidden=new string[] {
            "PaperType.Name"})]
    [MasterViewDefineAttribute("PrinterPaperE", "PaperType", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    public class PrinterPaper : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.PrintersAndPapers.PaperType fPaperType;
        
        private IIS.PrintersAndPapers.Printer fPrinter;
        
        // *** Start programmer edit section *** (PrinterPaper CustomMembers)

        // *** End programmer edit section *** (PrinterPaper CustomMembers)

        
        /// <summary>
        /// Printer paper.
        /// </summary>
        // *** Start programmer edit section *** (PrinterPaper.PaperType CustomAttributes)

        // *** End programmer edit section *** (PrinterPaper.PaperType CustomAttributes)
        [NotNull()]
        public virtual IIS.PrintersAndPapers.PaperType PaperType
        {
            get
            {
                // *** Start programmer edit section *** (PrinterPaper.PaperType Get start)

                // *** End programmer edit section *** (PrinterPaper.PaperType Get start)
                IIS.PrintersAndPapers.PaperType result = this.fPaperType;
                // *** Start programmer edit section *** (PrinterPaper.PaperType Get end)

                // *** End programmer edit section *** (PrinterPaper.PaperType Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (PrinterPaper.PaperType Set start)

                // *** End programmer edit section *** (PrinterPaper.PaperType Set start)
                this.fPaperType = value;
                // *** Start programmer edit section *** (PrinterPaper.PaperType Set end)

                // *** End programmer edit section *** (PrinterPaper.PaperType Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.PrintersAndPapers.Printer.
        /// </summary>
        // *** Start programmer edit section *** (PrinterPaper.Printer CustomAttributes)

        // *** End programmer edit section *** (PrinterPaper.Printer CustomAttributes)
        [Agregator()]
        [NotNull()]
        public virtual IIS.PrintersAndPapers.Printer Printer
        {
            get
            {
                // *** Start programmer edit section *** (PrinterPaper.Printer Get start)

                // *** End programmer edit section *** (PrinterPaper.Printer Get start)
                IIS.PrintersAndPapers.Printer result = this.fPrinter;
                // *** Start programmer edit section *** (PrinterPaper.Printer Get end)

                // *** End programmer edit section *** (PrinterPaper.Printer Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (PrinterPaper.Printer Set start)

                // *** End programmer edit section *** (PrinterPaper.Printer Set start)
                this.fPrinter = value;
                // *** Start programmer edit section *** (PrinterPaper.Printer Set end)

                // *** End programmer edit section *** (PrinterPaper.Printer Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "PrinterPaperE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View PrinterPaperE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("PrinterPaperE", typeof(IIS.PrintersAndPapers.PrinterPaper));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of PrinterPaper.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfPrinterPaper CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfPrinterPaper CustomAttributes)
    public class DetailArrayOfPrinterPaper : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.PrintersAndPapers.DetailArrayOfPrinterPaper members)

        // *** End programmer edit section *** (IIS.PrintersAndPapers.DetailArrayOfPrinterPaper members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type PrinterPaper by index.
        /// </summary>
        /// <summary>
        /// Adds object with type PrinterPaper.
        /// </summary>
        public DetailArrayOfPrinterPaper(IIS.PrintersAndPapers.Printer fPrinter) : 
                base(typeof(PrinterPaper), ((ICSSoft.STORMNET.DataObject)(fPrinter)))
        {
        }
        
        public IIS.PrintersAndPapers.PrinterPaper this[int index]
        {
            get
            {
                return ((IIS.PrintersAndPapers.PrinterPaper)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.PrintersAndPapers.PrinterPaper dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
